# Generated by Django 3.1 on 2021-01-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type_user', models.CharField(choices=[(None, 'Seleccione un tipo de usuario'), ('1', 'Administrador'), ('2', 'QuimicoSr'), ('3', 'QuimicoJr'), ('4', 'Paciente')], max_length=50)),
                ('creado_por', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('creado_por', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tipo_de_usuario', models.CharField(max_length=50)),
                ('id_email', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
