# Generated by Django 3.1 on 2021-01-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosistema',
            name='email',
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='id_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.email'),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
