# Generated by Django 3.1 on 2020-11-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201127_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='CELULAR_TELEFONO',
            new_name='CELULAR',
        ),
        migrations.AddField(
            model_name='medico',
            name='TELEFONO',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
