# Generated by Django 3.1 on 2021-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210122_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
