# Generated by Django 3.1 on 2020-11-28 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201127_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='COD',
        ),
        migrations.AlterField(
            model_name='medico',
            name='CEDULA',
            field=models.CharField(blank=True, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
