# Generated by Django 3.1 on 2020-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201127_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='CEDULA',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
